### ISSUE TITLE
Fix the typo

### ISSUE THREAD

**Issue by st1x51** [guard3/g3DTZ#1]
https://github.com/guard3/g3DTZ/blob/0793b22e22f3a518ff755ead16144945d302f712/source/extract/extractTimeCycle.cpp#L95

`<< '\t'      << static_cast<int>(pTimeCycle->m_nAmbientBlue[j][j])`
must be
`<< '\t'      << static_cast<int>(pTimeCycle->m_nAmbientBlue[j][i])`

**Comment by guard3** [comment]
@st1x51 Thank you for point that out! Fixed in latest commit https://github.com/guard3/g3DTZ/commit/7f0fe646a3e02a688151e21b4c74b09c8c4d6d82
